<?php


class MenuController extends Controller
{
    private $drink;
    private $accompaniment;
    private $sandwich;
    public function __construct($request)
    {
        parent::__construct($request);
        for($i=0;$i<sizeof($this->params);$i++){
            switch ($this->params[$i]){
                case 'all':
                    $this->drink=true;
                    $this->accompaniment=true;
                    $this->sandwich=true;
                    break;
                case 'drink':
                    $this->drink=true;
                    break;
                case 'accompaniment':
                    $this->accompaniment=true;
                    break;
                case 'sandwich':
                    $this->sandwich=true;
                    break;
                default:
                    $this->drink=false;
                    $this->accompaniment=false;
                    $this->sandwich=false;
            }

        }
    }

    public function get()
    {
        if(!$this->drink && !$this->sandwich && !$this->accompaniment){
            parent::get(); // TODO: Change the autogenerated stub
        }
        else{
            $d['Menu']=$this->loadModel('Menu')->readFirst($this->id);
            if($this->drink){
                $d['Menu']['Drink']=$this->loadModel('Drink')->readFirst($this->id);
            }
            if($this->sandwich){
                $d['Menu']['Sandwich']=$this->loadModel('Sandwich')->readFirst($this->id);
            }
            if($this->accompaniment){
                $d['Menu']['Accompaniment']=$this->loadModel('Accompaniment')->readFirst($this->id);
            }
            print_r(json_encode($d));
        }

    }
}