<?php


class SandwichController extends Controller
{
    private $bread;
    private $ingredient;
    public function __construct($request)
    {
        parent::__construct($request);
        for($i=0;$i<sizeof($this->params);$i++){
            switch ($this->params[$i]){
                case 'all':
                    $this->bread=true;
                    $this->ingredient=true;
                    break;
                case 'ingredient':
                    $this->ingredient=true;
                    break;
                case 'bread':
                    $this->bread=true;
                    break;
                default:
                    $this->bread=false;
                    $this->ingredient=false;
            }

        }
    }
    public function get()
    {

        if(!$this->bread && !$this->ingredient){
            parent::get(); // TODO: Change the autogenerated stub
        }
        else{
            $d['Sandwich']=$this->loadModel('Sandwich')->readFirst($this->id);
            if($this->bread){
                $d['Sandwich']['Bread']=$this->loadModel('Bread')->readFirst($d['Sandwich'][0]->id_bread);
            }
            if($this->ingredient){
                $d['Sandwich']['Ingredients']=$this->loadModel('IngredientList')->readSandwich($this->id);
            }
            print_r(json_encode($d));
        }

    }
}